# Generated by Django 5.0.1 on 2024-02-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/notfound.png', upload_to='images'),
        ),
    ]
