# Generated by Django 5.0.1 on 2024-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/notfound.png', upload_to='productlist/images'),
        ),
    ]
