# Generated by Django 5.0.1 on 2024-02-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='productlist/images/'),
        ),
    ]
