# Generated by Django 5.0.1 on 2024-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productlist', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/notfound.png', upload_to='productlist/images/'),
        ),
    ]
